env:
  CODECOV_TOKEN: 2a6bcc32-a9c4-4b07-976a-5759c17ec766
  JULIA_NUM_THREADS: auto
  
steps:
  - label: "CI Buildkite"
    plugins:
      - JuliaCI/julia#v1:
          version: "1"
      - QuantumSavory/julia-xvfb#v1:
      - JuliaCI/julia-test#v1: ~
      - JuliaCI/julia-coverage#v1:
          codecov: true
    command: |
      julia -e '
        using Pkg
        Pkg.add("QuantumSavory")
        Pkg.build("QuantumSavory")
        Pkg.test("QuantumSavory")'
