function _check_allrowscommute(Hx, Hz)
    for rowx in eachrow(Hx)
        for rowz in eachrow(Hz)
            comm = sum(rowx .& rowz)
            isodd(comm) && return false
        end
    end
    return true
end

"""
Construct a generalized Quantum Tanner code.

Returns `(𝒞ˣ, 𝒞ᶻ)` where `𝒞ˣ` is the X-stabilizer matrix and `𝒞ᶻ` is the Z-stabilizer matrix.

### Arguments
- `rate::Real`: Rate parameter for local codes (C_A has rate ρ, C_B has rate 1-ρ)
- `group`: The group G for the left-right Cayley complex
- `A`: Symmetric generating set A for the left Cayley graph
- `B`: Symmetric generating set B for the right Cayley graph  
- `bipartite::Bool`: Whether to use bipartite vertex partitioning (V₀, V₁)
"""
struct GeneralizedQuantumTannerCode <: AbstractCSSCode
    """The order of the underlying finite group"""
    group::Group
    """Generating set (closed under inverses) not containing the identity"""
    A::Vector{<:GroupElem}
    """Generating set (closed under inverses) not containing the identity"""
    B::Vector{<:GroupElem}
    """Tuple ((H_A, C_A), (H_B, C_B)) where (H_A, H_B) and (C_A, C_B) are parity-check and generator matrices, respectively."""
    classical_codes::Tuple{Tuple{Matrix{Int}, Matrix{Int}}, Tuple{Matrix{Int}, Matrix{Int}}}
    bipartite::Bool
    use_same_local_code::Bool

    function GeneralizedQuantumTannerCode(group::Group, A::Vector{<:GroupElem}, B::Vector{<:GroupElem},
                                         classical_codes::Tuple{Tuple{Matrix{Int}, Matrix{Int}}, Tuple{Matrix{Int}, Matrix{Int}}};
                                         bipartite=true, use_same_local_code=false)
        if bipartite
            @assert is_nonconjugate(group, A, B)
            @assert is_symmetric_gen(A)
            @assert is_symmetric_gen(B)
        end
        Δᴬ = length(A)
        Δᴮ = length(B)
        Hᴬ, Cᴬ = classical_codes[1]
        Hᴮ, Cᴮ = classical_codes[2]
        all(iszero, mod.(Hᴬ*transpose(Cᴬ), 2)) || @warn "C_A may not be a valid classical code: Hᴬ*Gᴬ^T ≠ 0"
        all(iszero, mod.(Hᴮ*transpose(Cᴮ), 2)) || @warn "C_B may not be a valid classical code: Hᴮ*Gᴮ^T ≠ 0"
        new(group, A, B, classical_codes, bipartite, use_same_local_code)
    end
end

function parity_matrix_xz(c::GeneralizedQuantumTannerCode)
    group, A, B, classical_codes, bipartite, use_same_local_code = c.group, c.A, c.B, c.classical_codes, c.bipartite, c.use_same_local_code
    Hᴬ, Cᴬ = classical_codes[1]
    Hᴮ, Cᴮ = classical_codes[2]
    if use_same_local_code
        Hᴮ = Hᴬ
    end
    R, _ = residue_ring(ZZ, 2)
    Hᴬ, Cᴬ, Hᴮ, Cᴮ = matrix(R, Hᴬ), matrix(R, Cᴬ), matrix(R, Hᴮ), matrix(R, Cᴮ)
    # "An X-type stabilizer generator is defined as a codeword from a generating set of
    # C₀ = C_A ⊗ C_B, with support on the faces incident to a given vertex in V₀ = V₀₀ ∪ V₁₁" [gu2022efficient](@cite)
    Cˣ = kronecker_product(Cᴬ, Cᴮ)
    # "Similarly, the Z-type stabilizers are generated by codewords of C₁ = C_A^⊥ ⊗ C_B^⊥
    # on the faces incident to vertices of V₁ = V₀₁ ∪ V₁₀" [gu2022efficient](@cite).
    Cᶻ = kronecker_product(Hᴬ, Hᴮ)
    @show size(Cˣ)
    @show size(Cᶻ)
    @assert good_css(Hᴬ, Cᴬ)
    @assert good_css(Hᴮ, Cᴮ)
    @assert good_css(Cˣ, Cᶻ)
    𝒢₀□, 𝒢₁□, edge₀_q_idx, edge₁_q_idx, edge₀_ab_idx, edge₁_ab_idx = bipartite ? cayley_complex_square_graphs(group, A, B) : cayley_complex_square_graphs_quadripartite(group, A, B)
    if bipartite
        𝒞ˣ = tanner_code(𝒢₀□, edge₀_q_idx, edge₀_ab_idx, Cˣ)  # X-stabilizers from C_A ⊗ C_B on V₀
        𝒞ᶻ = tanner_code(𝒢₁□, edge₁_q_idx, edge₁_ab_idx, Cᶻ)  # Z-stabilizers from C_A^⊥ ⊗ C_B^⊥ on V₁
    else
        𝒞ˣ = tanner_code_quadripartite(𝒢₀□, edge₀_q_idx, edge₀_ab_idx, Cˣ)
        𝒞ᶻ = tanner_code_quadripartite(𝒢₁□, edge₁_q_idx, edge₁_ab_idx, Cᶻ)
    end
    @show r1 = rank(𝒞ˣ)
    @show r2 = rank(𝒞ᶻ)
    @assert good_css(𝒞ˣ, 𝒞ᶻ)
    @assert _check_allrowscommute(𝒞ˣ, 𝒞ᶻ)
    return 𝒞ˣ, 𝒞ᶻ
end

parity_matrix_x(c::GeneralizedQuantumTannerCode) = parity_matrix_xz(c)[1]

parity_matrix_z(c::GeneralizedQuantumTannerCode) = parity_matrix_xz(c)[2]

function random_quantum_Tanner_code(ρ::Real, group::Group, A::Vector{<:GroupElem}, B::Vector{<:GroupElem}; bipartite=true, use_same_local_code=false)
    @show length(group), length(A), length(B)
    @show length(group)*length(A)*length(B)
    if bipartite
        @assert is_nonconjugate(group, A, B)
        @assert is_symmetric_gen(A)
        @assert is_symmetric_gen(B)
    end
    Δᴬ = length(A)
    Δᴮ = length(B)
    𝒢₀□, 𝒢₁□, edge₀_q_idx, edge₁_q_idx, edge₀_ab_idx, edge₁_ab_idx = bipartite ? cayley_complex_square_graphs(group, A, B) : cayley_complex_square_graphs_quadripartite(group, A, B)
    # "Let C_A, C_B ⊆ 𝔽₂^Δ be classical codes of rates ρ and (1-ρ) respectively" [gu2022efficient](@cite).
    # C_A has rate ρ, C_B has rate 1-ρ. For a code C with rate r = k/n, its dual C^⊥ has rate 1-r.
    # We consider H_A (parity check for C_A) defines C_A^⊥ which has rate 1-ρ.
    # We consider H_B (parity check for C_B) defines C_B^⊥ which has rate ρ.
    rate_Hᴬ = 1-ρ
    rate_Hᴮ = ρ
    Hᴬ = uniformly_random_code_checkmatrix(rate_Hᴬ, Δᴬ)
    Hᴮ = uniformly_random_code_checkmatrix(rate_Hᴮ, Δᴮ)
    @show Hᴬ
    @show Hᴮ
    if use_same_local_code
        Hᴮ = Hᴬ
    end
    # "The dual code of a code C is defined as C^⊥ = {x ∈ 𝔽₂ⁿ: ⟨x,y⟩=0 ∀ y ∈ C}" [gu2022efficient](@cite).
    Cᴬ = dual_code(Hᴬ)
    Cᴮ = dual_code(Hᴮ)
    @show Cᴬ
    @show Cᴮ
    # "An X-type stabilizer generator is defined as a codeword from a generating set of
    # C₀ = C_A ⊗ C_B, with support on the faces incident to a given vertex in V₀ = V₀₀ ∪ V₁₁" [gu2022efficient](@cite)
    Cˣ = kronecker_product(Cᴬ, Cᴮ)
    # "Similarly, the Z-type stabilizers are generated by codewords of C₁ = C_A^⊥ ⊗ C_B^⊥
    # on the faces incident to vertices of V₁ = V₀₁ ∪ V₁₀" [gu2022efficient](@cite).
    Cᶻ = kronecker_product(Hᴬ, Hᴮ)
    @show size(Cˣ)
    @show size(Cᶻ)
    @assert good_css(Hᴬ, Cᴬ)
    @assert good_css(Hᴮ, Cᴮ)
    @assert good_css(Cˣ, Cᶻ)
    if bipartite
        𝒞ˣ = tanner_code(𝒢₀□, edge₀_q_idx, edge₀_ab_idx, Cˣ)  # X-stabilizers from C_A ⊗ C_B on V₀
        𝒞ᶻ = tanner_code(𝒢₁□, edge₁_q_idx, edge₁_ab_idx, Cᶻ)  # Z-stabilizers from C_A^⊥ ⊗ C_B^⊥ on V₁
    else
        𝒞ˣ = tanner_code_quadripartite(𝒢₀□, edge₀_q_idx, edge₀_ab_idx, Cˣ)
        𝒞ᶻ = tanner_code_quadripartite(𝒢₁□, edge₁_q_idx, edge₁_ab_idx, Cᶻ)
    end
    @show r1 = rank(𝒞ˣ)
    @show r2 = rank(𝒞ᶻ)
    @assert good_css(𝒞ˣ, 𝒞ᶻ)
    @assert _check_allrowscommute(𝒞ˣ, 𝒞ᶻ)
    return 𝒞ˣ, 𝒞ᶻ
end

"""
Generate a good Quantum Tanner code meeting minimum weight requirements.

### Arguments
- `ρ`: Rate parameter for local codes
- `group`, `A`, `B`: Expander graph components  
- `minweight_x`: Minimum weight for X-stabilizers
- `minweight_z`: Minimum weight for Z-stabilizers
- `max_iterations`: Maximum attempts to find a good code
"""
function gen_good_code(ρ::Real, group::Group, A::Vector{<:GroupElem}, B::Vector{<:GroupElem}; minweight_x=1, minweight_z=1, bipartite=true, use_same_local_code=false, max_iterations=100)
    for i in 1:max_iterations
        𝒞ˣ, 𝒞ᶻ = random_quantum_Tanner_code(ρ, group, A, B; bipartite, use_same_local_code)
        x_weight = minimum(unique(sum(𝒞ˣ, dims=1)))
        z_weight = minimum(unique(sum(𝒞ᶻ, dims=1)))
        if x_weight >= minweight_x && z_weight >= minweight_z
            @assert _check_allrowscommute(𝒞ˣ, 𝒞ᶻ)
            return 𝒞ˣ, 𝒞ᶻ
        end
    end
    throw(ArgumentError("Failed to generate code meeting weight constraints after $max_iterations iterations"))
end
